### ISSUE TITLE
[Feature]: Allow OSQP hyperparameters to be passed into weights.qp

### ISSUE THREAD

**Issue by sk062380** [gchq/coreax#102]
### Is your proposal related to a problem?

coreax.weights.qp does not allow for passing of solve hyperparameters to jaxopt.OSQP  which is used within it.

### Describe the solution you would like*

Allow keyword arguments to be passed (ie. **kwargs) to coreax.weights.qp and then have these used within jaxpot.OSQP

### Code of Conduct*

- [X] I agree to follow this project's Code of Conduct

**Comment by pc532627** [comment]
Done as part of #632
