### ISSUE TITLE
Test kernel.compute for different shapes of input

### ISSUE THREAD

**Issue by sk062380** [gchq/coreax#237]
### Is your proposal related to a problem?

We should make sure kernel.compute works for different shapes of input since Stein herding uses different input shapes to the other types of herding that are implemented. 

### Describe the solution you would like*

Should just take a few unit tests to cover inputs as integer, vector, array etc.

### Code of Conduct*

- [X] I agree to follow this project's Code of Conduct

**Comment by tc85324** [comment]
This was covered in #543
