### ISSUE TITLE
Improve docstrings for refine

### ISSUE THREAD

**Issue by ghost** [gchq/coreax#265]
Some issues with the docstrings to fix:

- Line 121: `Refine._tree_unflatten` make verb a command: `Reconstruct`.
- Lines 132, 261, 483: remove the class name from the docstring. It adds nothing new. Instead, see whether you can shed more light on how we are refining and why refine. The docstring for `RefineReverse` is probably ok once the (old) class name has been removed.
- Change the annotation for any `random_key` to `ArrayLike`.

**Comment by pc532627** [comment]
Closed as part of #632
