### ISSUE TITLE
Update kernel calculation in metrics.py to support weighted inputs

### ISSUE THREAD

**Issue by bk958178** [gchq/coreax#376]
In metrics.py, in the method `weighted_maximum_mean_discrepancy_block()`, update the kernel matrix calculation from `self.sum_weighted_pairwise_distances()` to `self.kernel.calculate_K_sum()` when kernels support weighted inputs.

This may mean the class method `sum_weighted_pairwise_distances` can be deleted.

**Comment by tp832944** [comment]
Resolved in #632.
