### ISSUE TITLE
Fix tracing of score function in SteinKernel

### ISSUE THREAD

**Issue by bk958178** [gchq/coreax#377]
In `_tree_flatten()` in the SteinKernel class in kernel.py, the score function is assumed to not change so it is included in `aux_data` (static values). However, it might change if the kernel changes, so it should be moved from `aux_data` to `children` (dynamic values).

However, the method does not work when `self.score_function` is traced , i.e., when it is included in `children`.

**Comment by tp832944** [comment]
Equinox should handle this now. See PR #632.
