### ISSUE TITLE
Check for and remove gendered language

### ISSUE THREAD

**Issue by tp832944** [gchq/coreax#395]

**Comment by pc532627** [comment]
The codebase has been searched for the following examples of gendered language:
- Mr
- Miss
- Mrs
- Ms
- Man
- Men
- Woman
- Women
- Boy
- Boys
- Girl
- Girls
- Guy
- Guys
- Sir
- Madam
- He
- Him
- She
- Her
- Male
- Males
- Female
- Females
- Masculine 
- Feminine
- Lady
- Ladies
- Gentleman
- Gentlemen

I cannot find any instances of their usage - so I propose we close this ticket. @tp832944 - any issues with this?

**Comment by tp832944** [comment]
Happy to close.
