### ISSUE TITLE
Automatically update pre-commit package versions

### ISSUE THREAD

**Issue by tp832944** [gchq/coreax#429]
### Describe the feature that you would like.*

Automatically update pre-commit package versions without a maintainer needing to manually create a pull request.

### Why is this feature valuable to you?*

Maintainers no longer need to manually update periodically.

### Additional context

We could try this script https://browniebroke.com/blog/gh-action-pre-commit-autoupdate/.

Dependabot does not respect pip constraints, so is not great for updating requirements files. Perhaps we could use this approach here too? It would allow us to generate requirements files on other operating systems.

### Code of Conduct*

- [x] I agree to follow this project's Code of Conduct

**Comment by tp832944** [comment]
Plan is to use GitHub Actions like in #464.

**Comment by tc85324** [comment]
Could we run `pre-commit autoupdate` before running pre-commit in the existing `pre_commit_check.yml` then using the existing checkout action, commit an update to the pre-commit-file in the appropriate pull request/push to main?

**Comment by tp832944** [comment]
A package version update should go in its own PR because it could break things/require other changes to make the code pass. Create a new GitHub workflow. Use the `schedule` option to ask it to run once per fortnight (or once per week). One of us will need to manually approve and merge the automated PR.

Use the `gh` API so that the commits are signed by the GitHub Actions bot. Running commands like `git commit` directly in the Action will not create signed commits.
