### ISSUE TITLE
Tree Recombination

### ISSUE THREAD

**Issue by tc85324** [gchq/coreax#497]
### What's the new feature?

Sub task of #71

- ~~1-Tree (a.k.a. LittererLyons) recombination. Refs: [Litterer & Lyons 2012](https://arxiv.org/abs/1008.4942v2) and [Tchernychova 2015 Chapter 3.2 Algorithm 5](https://ora.ox.ac.uk/objects/uuid:a3a10980-d35d-467b-b3c0-d10d2e491f2d)~~
- M-Tree (a.k.a TchernychovaLyons) recombination Refs:  [Tchernychova 2015 Chapter 3.3 Algorithm 7](https://ora.ox.ac.uk/objects/uuid:a3a10980-d35d-467b-b3c0-d10d2e491f2d)

The SVD based Caratheodory reduction algorithm is shared across variations and can be implemented independent of the tree-based data structure. Feasibility and utility of the Tree-based data structures is to be determined. 

- See [here](https://github.com/FraCose/Recombination_Random_Algos/blob/2ca4ff74279eb1604376723dcb00ee65ff7e519a/recombination.py#L914) for a tree-free implementation in numpy/python.
- See [here](https://github.com/inakleinbottle/rustcombination/tree/master/src) for a tree implementation in rust.

TODO:
- [x] Add unit tests
- [x] Add performance tests
- [x] Add coresubset integration

### What value does this add?

Provides additional algorithms for generating coresets (reduced measures)

**Comment by tp832944** [comment]
Awaiting #581.

**Comment by tp832944** [comment]
Reassigning to @db091756 for tracking purposes and as likely reviewer. @tc85324 to continue as code author.
