### ISSUE TITLE
Consider usage of equinox

### ISSUE THREAD

**Issue by pc532627** [gchq/coreax#498]
### What's the new feature?

The package equinox (see https://docs.kidger.site/equinox/ and https://docs.kidger.site/equinox/api/module/advanced_fields/#checking-invariants) offers a replacement for the flax dependence, whilst also removing the need for `tree_flatten` and `tree_unflatten` methods. It might be useful to explore if incorporating this makes future development easier

### What value does this add?

Easier development of new classes due to the handling of `tree_flatten` and `tree_unflatten`, potentially useful to use the `__check_init__` method for validation

**Comment by tp832944** [comment]
This sounds like a better alternative to #220.

**Comment by tp832944** [comment]
Equinox is approved and in use in some upcoming PRs.
