### ISSUE TITLE
Coreset algorithm benchmarks for different data types

### ISSUE THREAD

**Issue by be904619** [gchq/coreax#509]
### What's the new feature?

Explore opportunities to identify benchmarks for application of different coreset algorithms to different types of data, providing objective recommendations.

### What value does this add?

This would give us greater insight into the application of different coreset algorithms to different data types, as well as providing a helpful starting point for users new to the package. This will help people apply and use the package more readily. 

### Additional context

This was a recommendation made during Sprint 15 Review.

**Comment by be904619** [comment]
Per @pc532627 there may be possible to combine this with #510

**Comment by be904619** [comment]
This becomes higher priority when recombination algorithms #71 and further alternative approaches are implemented.

**Comment by tp832944** [comment]
If we're talking about integers vs floats, take care as JAX has some interesting behaviour.
