### ISSUE TITLE
Performance regression testing

### ISSUE THREAD

**Issue by be904619** [gchq/coreax#510]
### What's the new feature?

Introducing a mechanism for regression testing of algorithm performance (in terms of speed).

### What value does this add?

This would support assessment of how performance either improves or regresses on development of new or existing features or software architecture. 

### Additional context

This was a recommendation made during Sprint 15 Review.

**Comment by tp832944** [comment]
Could be quite a large ticket. Depends on how thorough we want to be.

**Comment by tp832944** [comment]
If running during GitHub workflows, save timing data to a Git Gist.

**Comment by db091756** [comment]
Split this into issue #725
