### ISSUE TITLE
Add a class for coresubsets

### ISSUE THREAD

**Issue by tc85324** [gchq/coreax#518]
### What's the new feature?

Add a `CoreSubset` class like that shown below:

```python
# Current implementation
class KernelHearding(coreax.reduction.Coreset):
    self.coreset_indices = ... # some value that is set after a call to `fit_to_size`

# Proposed implementation
class CoreSubset(coreax.reduction.Coreset):
      """Docstring explaining that a coresubset is a special type of coreset"""
      self.coreset_indices = None  # Remove from Coreset and init here as None

class KernelHearding(CoreSubset):
      self.coreset_indices = ... # some value that is overwritten from `None` after a call to `fit_to_size`
```

### What value does this add?

At the moment, a child of `Coreset` is considered as a coresubset if the `Coreset.corset_indices is not None`. This kind of implicit "typing" can be confusing for new users, and makes it impossible to determine the "type" of coreset algorithm being used at runtime (prior to fitting, all corsets have `Corset.corset_indices = None`)

*Documentation example:* if the `KernelHerding` class were not in the `coresubset.py` file, which may not be the case for future coresubset algorithms, the only way to determine that it is a coresubset (not a coreset) is to inspect the code in its `fit_to_size` method. This assumes the user is already aware that setting a `coreset_indices != None` indicates a coresubset algorithm. If `KernelHerding` was a child of a `CoreSubset` class, it is immediately obvious that it generates a coresubset, and that the important documentation regarding the difference between a `Coreset` and a `Coresubset` can be found by going to the definition of `CoreSubset`.

*Runtime example:* imagine a user wishes to construct a searchable set of `Coreset` classes/algorithms. Currently, there is no option to filter such a set to only `CoreSubsets`. However, if the coresubset methods all inherited from a `CoreSubset` class, it would be as simple as `filter(lambda x: isinstance(x, CoreSubset), searchable_set)`. You could even do something like [this](https://stackoverflow.com/questions/3862310/how-to-find-all-the-subclasses-of-a-class-given-its-name) if you wanted to programmatically identify all `CoreSubsets` implemented in coreax.

### Is there an alternative you've considered?

Continue with the current approach.

**Comment by tp832944** [comment]
A further advantage of only defining `coreset_indices` on `CoreSubset` is that we guard against silent failures when `coreset_indices` is `None` but should be an array. After this change, `coreset_indices` would always be an array for a `CoreSubset` or undefined and raise an `AttributeError` for any other `Coreset`. Credit: @rg936672.
