### ISSUE TITLE
Prefix abstract classes with "Abstract"

### ISSUE THREAD

**Issue by tc85324** [gchq/coreax#519]
### What's the new feature?

To make it as obvious as possible to new/existing users that a class is abstract (has methods that child classes must implement) prefix their names as follows:
```python
# Current implementation
class Coreset(ABC)
    ...
# Proposed implementation
class AbstractCoreset(ABC)
    ...
```

### What value does this add?

Enhances code clarity and interpretability. Also makes it very easy to adopt a "concrete is final" design pattern in the future (particularly useful if we chose to adopt equinox #498, which provides the "eqx.Module(strict=True)" option for strictly enforcing such a pattern).

### Is there an alternative you've considered?

Continue with the current approach.

**Comment by tp832944** [comment]
Worth discussing. If we do add a prefix, I think `Base` would be more in line with other Python libraries.

**Comment by tp832944** [comment]
We decided better to leave as is.
