### ISSUE TITLE
`Refine.refine` should accept a kernel in its call signature

### ISSUE THREAD

**Issue by tc85324** [gchq/coreax#534]
### What's the new feature?

Modify the call signature of refine:
```Python
# Current implementation
class Refine(...):
    def refine(self, coreset: coreax.reduction.Coreset) -> None:
        coreset.kernel.calculate_kernel_matrix_row_sum_mean(coreset.original_data.pre_coreset_array)

# Proposed implementation
class Refine(...):
    def refine(self, coreset: coreax.reduction.Coreset, kernel:coreax.kernel.Kernel) -> None:
        kernel.calculate_kernel_matrix_row_sum_mean(coreset.original_data.pre_coreset_array)
```

### What value does this add?

- `Core(sub)set` is not required to have a `kernel` attribute if it will only be used in `Refine`.
- Allow a different kernel to be used in refinement than used in `Core(sub)set` which does require a `kernel` attribute (E.G. `KernelHearding` can have a `kernel` attribute which defines a different kernel to the one used in the refinement step).

**Comment by tp832944** [comment]
After discussion, we have agreed that this would be a worthwhile change. `Refine.refine` will now take kernel as a parameter. `Coreset.refine` will populate the kernel parameter of `Refine.refine` with the kernel in `Coreset.kernel`.

**Comment by tp832944** [comment]
@tc85324 what is blocking this? Please tag the relevant tickets in the description or as a comment.
