### ISSUE TITLE
CLA assistant needs to allow bot contribution for pre-commit autoupdate workflow

### ISSUE THREAD

**Issue by tc85324** [gchq/coreax#536]
### What's the problem?

In pull #535, the bot has not been exempted from signing the CLA. 
This can be fixed by following the instructions [here](https://github.com/cla-assistant/cla-assistant?tab=readme-ov-file#can-i-allow-bot-user-contributions)

### How can we reproduce the issue?

See pull #535

### Python version

3.9, 3.10, 3.11

### Package version

0.1.0

### Operating system

Ubuntu 23.04.2

**Comment by tp832944** [comment]
Not critical as can still merge bot PRs, but would make it easier to review PRs, as this appears as a GitHub workflow failure.

**Comment by gchqdev227** [comment]
This has now been resolved and the bot has been added to the exception list for the CLA bot.  If a PR is currently showing as unsigned then click the "recheck" button in the bot comment to reassess, and it should go green.
