### ISSUE TITLE
Define mix-in class for coreset with kernel

### ISSUE THREAD

**Issue by tp832944** [gchq/coreax#545]
### What's the new feature?

`Coreset` will only contain the bare minimum set of attributes and methods, as the base class. Not all coreset methods use a kernel, so `kernel` should be removed from `Coreset`. Instead, a coreset with kernel class, which inherits from `Coreset`, should be defined.

This is similar to the mix-in classes used by Scikit-learn.

### What value does this add?

Different base class specialisms of `Coreset` can be defined, with another important one being `Coresubset` - see #518. If the user wants a coresubset with a kernel, their coreset class should inherit from both,

```python
class CustomCoreset(Coresubset, CoresetWithKernel):
```

**Comment by pc532627** [comment]
We now use solver state instead to preserve such quantities.
