### ISSUE TITLE
Documentation GitHub workflow failing

### ISSUE THREAD

**Issue by tp832944** [gchq/coreax#561]
### What's the problem?

The build is generating the warning

```
pickling environment... WARNING: cannot cache unpickable configuration value: 'typehints_formatter'
```

This is only a warning so the build does succeed but the GitHub workflow fails as we've got it set to fail on warnings.

### How can we reproduce the issue?

https://github.com/gchq/coreax/actions/runs/8719140758/job/23917872705

### Python version

3.11, 3.12

### Package version

0.1.0

### Operating system

Linux, Windows

### Other packages

Dependency updates that seem to have triggered the issue:

docutils 0.20.1->0.21.1
sphinx 7.2.6->7.3.5

**Comment by AA-Turner** [comment]
xref: https://github.com/sphinx-gallery/sphinx-gallery/issues/1286

A
