### ISSUE TITLE
Enable ruff check for `eval` usage

### ISSUE THREAD

**Issue by tp832944** [gchq/coreax#597]
### What's the new feature?

Check for dangerous uses of inbuilt `eval` using ruff check S307 https://docs.astral.sh/ruff/rules/suspicious-eval-usage/. Then can remove pre-commit hook `python-no-eval`.

### What value does this add?

Remove a separate pre-commit hook.

**Comment by tc85324** [comment]
Can add `S102` for exec usage as well
