### ISSUE TITLE
Add coreset algorithms

### ISSUE THREAD

**Issue by db091756** [gchq/coreax#651]
### What's the new feature?

Add the following coreset algorithms:

1.  Kernel Thinning #688 (unsupervised), kind of similar to Kernel Herding but with stronger guarantees, will probably be tricky to implement in JAX as it relies on recursion.
1. Kernel Inducing Points #606 (supervised), will be very useful for the future.
2.  Data Twinning #687 (unsupervised & supervised), targets the [Energy Distance](https://en.wikipedia.org/wiki/Energy_distance) as a metric
3. Bayesian Coreset algorithms #689 (unsupervised & supervised), currently no Bayesian functionality in Coreax, do we want it?

Also see #690 for a few sketching algorithms that could be added.

### What value does this add?

Expands coreax functionality

**Comment by bk958178** [comment]
Closing following team discussion

**Comment by db091756** [comment]
We will not be implementing these as a team, but we welcome outside contributions for this ticket
