### ISSUE TITLE
Release version number does not match version number in `__init__.py`

### ISSUE THREAD

**Issue by tc85324** [gchq/coreax#680]
### What's the problem?

The version number in `__init__.py` is `v0.1.0`, the latest release is `v0.2.0`.

### How can we reproduce the issue?

Install coreax from main, then run:
```python
import coreax
print(coreax.__version__)  # 0.1.0
```

### Python version

3.9, 3.10, 3.11, 3.12

### Package version

0.1.0

### Operating system

Ubuntu

**Comment by tp832944** [comment]
Same PR as #681.
