### ISSUE TITLE
Release v0.2.1

### ISSUE THREAD

**Issue by tp832944** [gchq/coreax#681]
### What's the issue?

Primarily to fix incorrect version number - see #680.

**Comment by tp832944** [comment]
Awaiting PyPI and RtD permissions. Expected next week.

**Comment by tl82649** [comment]
@tp832944: 0.2.0 is up on PyPI and ReadTheDocs. The version in `__init.py__` will presumably need to change to allow correct versioning display on the ReadTheDocs splash page.

**Comment by tp832944** [comment]
Published.
