### ISSUE TITLE
Private members are included in documentation

### ISSUE THREAD

**Issue by rg936672** [gchq/coreax#735]
### What's the issue?

Remove `"private-members": True` from `autodoc_default_options` in `conf.py`. Have a check through the documentation to ensure that we're not hiding anything that _should_ actually be public despite being prefixed with an underscore. If we are, add special-case exemptions for them.

**Comment by db091756** [comment]
I am happy for this to be a simple one-line PR changing `True` to `False`. I think all private functions and methods in the repo are fine to be undocumented
