### ISSUE TITLE
New coreax release v0.3

### ISSUE THREAD

**Issue by bk958178** [gchq/coreax#766]
The new version should not introduce any breaking changes, i.e. that would break existing functionality for users. Any changes that might eventually lead to breaking functionality should be marked as deprecated.

**Comment by bk958178** [comment]
Blocked by #764

**Comment by tc85324** [comment]
As a reminder, we have some deprecated features marked for removal at v0.3. It would be nice to release v0.3 once #504 is merged, which will hopefully be before next week. I think this would provide a significant enough change to justify v0.3 over v0.2.2.

**Comment by tp832944** [comment]
Blocked by #779.
