### ISSUE TITLE
Move coverage/performance data from personal Gist to an organisation-level location

### ISSUE THREAD

**Issue by tp832944** [gchq/coreax#776]
### What's the issue?

The coverage and performance data are currently written to a GitHub Gist hosted by @tp832944. It will be more maintainable to write it to a location where all repo maintainers can be maintainers of the location.

Suggestion: a full GitHub repo hosted by our organisation.

**Comment by tp832944** [comment]
Blocked awaiting internal decision on best way forwards.

**Comment by tp832944** [comment]
Still awaiting internal decision.

**Comment by tp832944** [comment]
Repo now being set up.

**Comment by pc532627** [comment]
Waiting internal actions.
