### ISSUE TITLE
Write integration test for tree recombination

### ISSUE THREAD

**Issue by tp832944** [gchq/coreax#778]
### What's the issue?

No end-to-end test exists for tree recombination, which also means we're lacking an example.

**Comment by tp832944** [comment]
@tc85324 do you have any suggestions for input functions to use?

**Comment by tc85324** [comment]
I have an existing notebook, which uses degree-m multi-variate polynomials as the test-functions, with the original dataset being a degree-m product cubature formula for exactly integrating these polynomials over the hypercube and the recombination solver yielding a coreset (a non-product cubature formula of the same degree). 

I will attempt to port this notebook into the examples before next week.
