### ISSUE TITLE
Fix the plot of David example when using downsampling

### ISSUE THREAD

**Issue by qh681248** [gchq/coreax#808]
### What's the problem?

When down sampling, the original plot of the David image does not look like David at all. Track what is causing this problem.

### How can we reproduce the issue?

Change downsampling factor to 4 or some number other than 1 on `david.py` and run

### Python version

3.12

### Package version

0.2.1

### Operating system

Windows

**Comment by pc532627** [comment]
After investigation, there is no issue with this piece of code. The image in question is just sufficiently low resolution that if it is down sampled by a factor of 4, there is no detail remaining and it appears to be noise. If it is down sampled by a factor of 2, you can see slight detail, but beyond this the image just becomes unrecognisable. No changes needed.
