### ISSUE TITLE
0.3.0 release missing `coreax.kernels`

### ISSUE THREAD

**Issue by richardmillson** [gchq/coreax#843]
### What's the problem?

`coreax` [0.3.0](https://github.com/gchq/coreax/blob/main/CHANGELOG.md#030) refactored `coreax.kernel.py` into a `coreax.kernels` sub-package, however `coreax.kernels` doesn't appear to have been included in the release and is missing from
the [tar](https://files.pythonhosted.org/packages/98/15/37fc3a59434dc9734a5dd8f192be19521deddeb5f3a360cddecf0d9475c3/coreax-0.3.0.tar.gz) and [whl](https://files.pythonhosted.org/packages/77/04/e7897db8412b576b4cf1eeee123215cf6b1aba2e90caa675ca9afc75449a/coreax-0.3.0-py3-none-any.whl).

### How can we reproduce the issue?

```shell
> python3 -m pip install jax
> python3 -m pip install coreax
> python -m pip list | grep -i coreax
coreax                                   0.3.0
> python3 -c "import coreax"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.10/site-packages/coreax/__init__.py", line 28, in <module>
    from coreax.approximation import (
  File "/opt/conda/lib/python3.10/site-packages/coreax/approximation.py", line 43, in <module>
    from coreax.kernels import UniCompositeKernel
ModuleNotFoundError: No module named 'coreax.kernels'
```

### Python version

3.10, 3.11, 3.12

### Package version

0.3.0

### Operating system

Linux

### Other packages

`coreax` (and `jax`) were installed in a new conda environment.

**Comment by richardmillson** [comment]
`coreax.solvers` appears to be missing as well
```shell
> python3 -c "from coreax.solvers import *"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'coreax.solvers'
```

**Comment by tp832944** [comment]
Hi @richardmillson, thank you for raising this. We'll investigate what went wrong in the build and release an update soon.
