### ISSUE TITLE
On GPU, TestCaratheodoryRecombination is failing

### ISSUE THREAD

**Issue by tp832944** [gchq/coreax#853]
### What's the problem?

On NVIDIA GPU, TestCaratheodoryRecombination is failing.

### How can we reproduce the issue?

Run  tests/unit/test_solvers.py::TestCaratheodoryRecombination

### Python version

3.12

### Package version

0.3.1

### Operating system

Ubuntu 24.04 with NVIDIA GPU

### Other packages

jax[cuda12]

### Relevant log output

FAILED tests/unit/test_solvers.py::TestCaratheodoryRecombination::test_reduce[with_jit-random-implicit-explicit-context0-False] - assert Array(False, dtype=bool)
FAILED tests/unit/test_solvers.py::TestCaratheodoryRecombination::test_reduce[with_jit-random-implicit-explicit-context0-True] - assert Array(False, dtype=bool)
FAILED tests/unit/test_solvers.py::TestCaratheodoryRecombination::test_reduce[with_jit-partial-null-implicit-explicit-context0-False] - assert Array(False, dtype=bool)
FAILED tests/unit/test_solvers.py::TestCaratheodoryRecombination::test_reduce[with_jit-partial-null-implicit-explicit-context0-True] - assert Array(False, dtype=bool)
FAILED tests/unit/test_solvers.py::TestCaratheodoryRecombination::test_reduce[with_jit-partial-null-implicit-context1-False] - assert Array(False, dtype=bool)
FAILED tests/unit/test_solvers.py::TestCaratheodoryRecombination::test_reduce[with_jit-partial-null-implicit-context1-True] - assert Array(False, dtype=bool)
FAILED tests/unit/test_solvers.py::TestCaratheodoryRecombination::test_reduce[without_jit-partial-null-implicit-explicit-context0-False] - assert Array(False, dtype=bool)
FAILED tests/unit/test_solvers.py::TestCaratheodoryRecombination::test_reduce[without_jit-partial-null-implicit-explicit-context0-True] - assert Array(False, dtype=bool)
FAILED tests/unit/test_solvers.py::TestCaratheodoryRecombination::test_reduce[without_jit-partial-null-implicit-context1-False] - assert Array(False, dtype=bool)
FAILED tests/unit/test_solvers.py::TestCaratheodoryRecombination::test_reduce[without_jit-partial-null-implicit-context1-True] - assert Array(False, dtype=bool)
FAILED tests/unit/test_solvers.py::TestCaratheodoryRecombination::test_reduce[without_jit-partial-null-explicit-context2-False] - assert Array(False, dtype=bool)
FAILED tests/unit/test_solvers.py::TestCaratheodoryRecombination::test_reduce[without_jit-partial-null-explicit-context2-True] - assert Array(False, dtype=bool)
FAILED tests/unit/test_solvers.py::TestCaratheodoryRecombination::test_reduce[without_jit-random-implicit-explicit-context0-False] - assert Array(False, dtype=bool)
FAILED tests/unit/test_solvers.py::TestCaratheodoryRecombination::test_reduce[without_jit-random-implicit-explicit-context0-True] - assert Array(False, dtype=bool)
FAILED tests/unit/test_solvers.py::TestCaratheodoryRecombination::test_reduce[without_jit-random-explicit-context2-False] - assert 25 <= Array(11, dtype=int32)
FAILED tests/unit/test_solvers.py::TestCaratheodoryRecombination::test_reduce[without_jit-random-explicit-context2-True] - assert 25 <= Array(11, dtype=int32)
FAILED tests/unit/test_solvers.py::TestCaratheodoryRecombination::test_reduce[without_jit-null-implicit-explicit-context0-False] - assert 11 <= (11 - (11 - Array(1, dtype=int32)))
FAILED tests/unit/test_solvers.py::TestCaratheodoryRecombination::test_reduce[without_jit-null-implicit-explicit-context0-True] - assert 11 <= (11 - (11 - Array(1, dtype=int32)))
FAILED tests/unit/test_solvers.py::TestCaratheodoryRecombination::test_reduce[without_jit-null-explicit-context2-False] - assert 23 <= Array(1, dtype=int32)
FAILED tests/unit/test_solvers.py::TestCaratheodoryRecombination::test_reduce[without_jit-null-explicit-context2-True] - assert 23 <= Array(1, dtype=int32)
FAILED tests/unit/test_solvers.py::TestCaratheodoryRecombination::test_reduce[with_jit-null-implicit-explicit-context0-False] - assert 11 <= (11 - (11 - Array(1, dtype=int32)))
FAILED tests/unit/test_solvers.py::TestCaratheodoryRecombination::test_reduce[with_jit-null-implicit-explicit-context0-True] - assert 11 <= (11 - (11 - Array(1, dtype=int32)))
FAILED tests/unit/test_solvers.py::TestCaratheodoryRecombination::test_reduce[without_jit-full_rank-implicit-explicit-context0-False] - assert Array(False, dtype=bool)
FAILED tests/unit/test_solvers.py::TestCaratheodoryRecombination::test_reduce[without_jit-full_rank-implicit-explicit-context0-True] - assert Array(False, dtype=bool)
FAILED tests/unit/test_solvers.py::TestCaratheodoryRecombination::test_reduce[without_jit-full_rank-explicit-context2-False] - assert 18 <= Array(4, dtype=int32)
FAILED tests/unit/test_solvers.py::TestCaratheodoryRecombination::test_reduce[without_jit-full_rank-explicit-context2-True] - assert 18 <= Array(4, dtype=int32)
FAILED tests/unit/test_solvers.py::TestCaratheodoryRecombination::test_reduce[with_jit-full_rank-implicit-explicit-context0-False] - assert Array(False, dtype=bool)
FAILED tests/unit/test_solvers.py::TestCaratheodoryRecombination::test_reduce[with_jit-full_rank-implicit-explicit-context0-True] - assert Array(False, dtype=bool)
FAILED tests/unit/test_solvers.py::TestCaratheodoryRecombination::test_reduce[without_jit-rank_deficient-implicit-explicit-context0-False] - assert Array(False, dtype=bool)
FAILED tests/unit/test_solvers.py::TestCaratheodoryRecombination::test_reduce[without_jit-rank_deficient-implicit-explicit-context0-True] - assert Array(False, dtype=bool)
FAILED tests/unit/test_solvers.py::TestCaratheodoryRecombination::test_reduce[without_jit-rank_deficient-explicit-context2-False] - assert 26 <= Array(2, dtype=int32)
FAILED tests/unit/test_solvers.py::TestCaratheodoryRecombination::test_reduce[without_jit-rank_deficient-explicit-context2-True] - assert 26 <= Array(2, dtype=int32)
FAILED tests/unit/test_solvers.py::TestCaratheodoryRecombination::test_reduce[with_jit-rank_deficient-implicit-explicit-context0-False] - assert Array(False, dtype=bool)
FAILED tests/unit/test_solvers.py::TestCaratheodoryRecombination::test_reduce[with_jit-rank_deficient-implicit-explicit-context0-True] - assert Array(False, dtype=bool)

**Comment by tc85324** [comment]
See https://github.com/gchq/coreax/issues/852#issuecomment-2496225349
