### ISSUE TITLE
Add Square-root kernels

### ISSUE THREAD

**Issue by qh681248** [gchq/coreax#867]
### What's the new feature?

See Section 2.2, Definition 5 (https://arxiv.org/abs/2105.05842) for the definition of square-root kernel, 
![Image](https://github.com/user-attachments/assets/3b40e941-ca4e-46b1-8ea7-fce3e52fc824),

For the Squared Exponential Kernel, Matern Kernel and Beta-Spline kernel, the square root kernels can be found and are the same kernels with different parameters.

For the rest of the kernels, a square root dominating kernel (not exactly square root but good enough for applications like Kernel Thinning) can be found, see the same paper, Appendix Q (https://arxiv.org/pdf/2105.05842)

![Image](https://github.com/user-attachments/assets/e7c964df-d0af-4fb6-9c36-5a6f047d83e2)

### What value does this add?

It helps the user use Kernel Thinning with various kernels for instance

**Comment by gw265981** [comment]
We have provisionally agreed to add them as a method for ScalarValuedKernel. For now, we can just add the few that have an easy analytic form in the paper.
